dbdsn="file:./vol/db.sqlite"
admin_user = "admin"
admin_password = "adminpass"
site_name = "话说"
site_description = "想说什么都可以"
srvMode="debug"
[object_storage]
aws_access_key_id = "******"
aws_secret_access_key = "******"
aws_region = "us-east-1"
aws_bucket = "www.domain.com"
cdn_url = "//www.domain.com"